FROM nginx:alpine

RUN date | tee /usr/share/nginx/html/version.txt /usr/share/nginx/html/index.html
COPY output-stops /usr/share/nginx/html/hsl/stops
COPY output-routes /usr/share/nginx/html/hsl/routes
COPY nginx.template /etc/nginx/nginx.template

CMD /bin/sh -c "envsubst < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"