FROM nginx:alpine

RUN date | tee /usr/share/nginx/html/version.txt /usr/share/nginx/html/index.html
COPY output-stops /usr/share/nginx/html/hsl/stops
COPY output-routes /usr/share/nginx/html/hsl/routes
COPY nginx.conf /etc/nginx/nginx.conf

CMD /bin/sh -c "exec nginx -g 'daemon off;'"